### ISSUE TITLE
If I use an empty password for Digest Auth, Authorization header is not generated

### ISSUE THREAD

**Issue by yca-estos** [ok2c/httpclient-android-ext#4]
Code is throwing exception in DigestScheme.java line 312 (or 319, depending on algorithm) while trying to append an empty password (CharArray).
<img width="926" alt="Screen Shot 2022-01-23 at 20 23 44" src="https://user-images.githubusercontent.com/91329898/150694709-0a2995b5-4977-4cc0-884d-ae358e6f5251.png">

**Comment by ok2c** [comment]
@yca-estos Screenshots are not very useful in bug reports. 
1. Please provide the _exact_ exception stack trace thrown.
2. Please mention the _exact_version of Apache HttpClient you are using.
3. Please provide a reproducer in a form a test case or sequence steps to be taken to trigger the reported defect.

**Comment by yca-estos** [comment]
1. Stacktrace:
```
2022-01-24 11:31:56.741 W/System.err: java.lang.IllegalStateException: Current state = RESET, new state = FLUSHED
2022-01-24 11:31:56.742 W/System.err:     at java.nio.charset.CharsetEncoder.throwIllegalStateException(CharsetEncoder.java:1021)
2022-01-24 11:31:56.743 W/System.err:     at java.nio.charset.CharsetEncoder.flush(CharsetEncoder.java:694)
2022-01-24 11:31:56.743 W/System.err:     at org.apache.hc.client5.http.utils.ByteArrayBuilder.encode(ByteArrayBuilder.java:83)
2022-01-24 11:31:56.744 W/System.err:     at org.apache.hc.client5.http.utils.ByteArrayBuilder.doAppend(ByteArrayBuilder.java:107)
2022-01-24 11:31:56.744 W/System.err:     at org.apache.hc.client5.http.utils.ByteArrayBuilder.append(ByteArrayBuilder.java:149)
2022-01-24 11:31:56.744 W/System.err:     at org.apache.hc.client5.http.utils.ByteArrayBuilder.append(ByteArrayBuilder.java:161)
2022-01-24 11:31:56.745 W/System.err:     at org.apache.hc.client5.http.utils.ByteArrayBuilder.append(ByteArrayBuilder.java:168)
2022-01-24 11:31:56.746 W/System.err:     at org.apache.hc.client5.http.impl.auth.DigestScheme.createDigestResponse(DigestScheme.java:319)
2022-01-24 11:31:56.746 W/System.err:     at org.apache.hc.client5.http.impl.auth.DigestScheme.generateAuthResponse(DigestScheme.java:206)
2022-01-24 11:31:56.746 W/System.err:     at org.apache.hc.client5.http.impl.auth.HttpAuthenticator.addAuthResponse(HttpAuthenticator.java:327)
2022-01-24 11:31:56.747 W/System.err:     at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:160)
2022-01-24 11:31:56.747 W/System.err:     at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
2022-01-24 11:31:56.748 W/System.err:     at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
2022-01-24 11:31:56.748 W/System.err:     at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:93)
2022-01-24 11:31:56.748 W/System.err:     at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
2022-01-24 11:31:56.749 W/System.err:     at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
2022-01-24 11:31:56.749 W/System.err:     at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:128)
2022-01-24 11:31:56.750 W/System.err:     at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
2022-01-24 11:31:56.750 W/System.err:     at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
2022-01-24 11:31:56.751 W/System.err:     at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
2022-01-24 11:31:56.751 W/System.err:     at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
2022-01-24 11:31:56.751 W/System.err:     at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:178)
2022-01-24 11:31:56.752 W/System.err:     at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:75)
2022-01-24 11:31:56.752 W/System.err:     at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:89)
```

2. version used: 0.1.1

3. sample code to reproduce issue 
```
            val credentialStore: CredentialsStore = BasicCredentialsProvider()
            credentialStore.setCredentials(
                    AuthScope(null, null, -1, null, "Digest"),
                    UsernamePasswordCredentials("user", "".toCharArray()))

            val httpClient = HttpClients.custom()
                    .setDefaultCredentialsProvider(credentialStore)
                    .build()

            val request = HttpGet("http://httpbin.org/digest-auth/auth/user/password")
            request.config = RequestConfig.custom().setTargetPreferredAuthSchemes(listOf("Digest")).setAuthenticationEnabled(true).build()
            var response: CloseableHttpResponse? = null
            try {
                response = httpClient.execute(request)
            } catch (e: Exception) {
                e.printStackTrace()
            }
            response?.close()
            httpClient.close()
```

**Comment by ok2c** [comment]
@yca-estos I can reproduce the defect with the latest snapshot of HttpClient 5.1 and 5.2. I am working on a fix.

**Comment by ok2c** [comment]
@yca-estos Fixed in Apache HttpClient  https://github.com/apache/httpcomponents-client/commit/a963001b776125ef29bfc0bf77adf5b60fea2a98

**Comment by yca-estos** [comment]
Sorry if this is a stupid question :) but is there any way so that I can use this fixed version as dependency in my project?

**Comment by ok2c** [comment]
@yca-estos You can. You need to build the latest snapshot from source or wait for an official 5.1.3 release

**Comment by yca-estos** [comment]
ok thanks
